// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZL5AMjbIDcugRZT8ICD5GL7w0WldNdUY',
    appId: '1:435824970238:web:eb558cf86bea7edd62d8af',
    messagingSenderId: '435824970238',
    projectId: 'medtrackjgf',
    authDomain: 'medtrackjgf.firebaseapp.com',
    storageBucket: 'medtrackjgf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrvibu0gXNNhdZqJ0V8lt_x9tx4CA5Yo',
    appId: '1:435824970238:android:7274bacb73fab8e062d8af',
    messagingSenderId: '435824970238',
    projectId: 'medtrackjgf',
    storageBucket: 'medtrackjgf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXCuavhXUqfHZ3eV_kbg5Kn0DAxuFFek',
    appId: '1:435824970238:ios:ffa822d4ea7bc56562d8af',
    messagingSenderId: '435824970238',
    projectId: 'medtrackjgf',
    storageBucket: 'medtrackjgf.firebasestorage.app',
    iosBundleId: 'com.example.medtrackApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXCuavhXUqfHZ3eV_kbg5Kn0DAxuFFek',
    appId: '1:435824970238:ios:ffa822d4ea7bc56562d8af',
    messagingSenderId: '435824970238',
    projectId: 'medtrackjgf',
    storageBucket: 'medtrackjgf.firebasestorage.app',
    iosBundleId: 'com.example.medtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZL5AMjbIDcugRZT8ICD5GL7w0WldNdUY',
    appId: '1:435824970238:web:f4935f85b8b2703e62d8af',
    messagingSenderId: '435824970238',
    projectId: 'medtrackjgf',
    authDomain: 'medtrackjgf.firebaseapp.com',
    storageBucket: 'medtrackjgf.firebasestorage.app',
  );
}
